In [52]:
# modules
import pandas
import numpy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LassoCV
from sklearn.model_selection import RepeatedKFold

from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

import statsmodels.api as sm
from sklearn.metrics import mean_squared_error

In [16]:
rentData = pandas.read_csv("housing_train.csv")
# combine state and region data
rentData["stateRegion"] = rentData["state"] + " " + rentData["region"]
# drop columns that are not needed
rentData.drop(['url', 'region_url', 'description', 'lat', 'long', 'image_url', 'region', 'state'], axis=1, inplace=True)

In [20]:
rentData.head(5)

,id,price,type,sqfeet,beds,baths,cats_allowed,dogs_allowed,smoking_allowed,wheelchair_access,electric_vehicle_charge,comes_furnished,laundry_options,parking_options,stateRegion
0,7039061606,1195,apartment,1908,3,2.0,1,1,1,0,0,0,laundry on site,street parking,al birmingham
1,7041970863,1120,apartment,1319,3,2.0,1,1,1,0,0,0,laundry on site,off-street parking,al birmingham
2,7041966914,825,apartment,1133,1,1.5,1,1,1,0,0,0,laundry on site,street parking,al birmingham
3,7041966936,800,apartment,927,1,1.0,1,1,1,0,0,0,laundry on site,street parking,al birmingham
4,7041966888,785,apartment,1047,2,1.0,1,1,1,0,0,0,laundry on site,street parking,al birmingham

In [ ]:
# turn categorical data into dummy variables
# drop first for all dummy variables to get to k-1 columns, and set type to float
geo_dummies = pandas.get_dummies(rentData['stateRegion'], drop_first=True, dtype=float)
geo_dummies = geo_dummies.add_prefix('stateRegion_')
type_dummies = pandas.get_dummies(rentData['type'], drop_first=True, dtype=float)
type_dummies = type_dummies.add_prefix('type_')
laundry_dummies = pandas.get_dummies(rentData['laundry_options'], drop_first=True, dtype=float)
laundry_dummies = laundry_dummies.add_prefix('laundry_')
parking_dummies = pandas.get_dummies(rentData['parking_options'], drop_first=True, dtype=float)
parking_dummies = parking_dummies.add_prefix('parking_')

In [26]:
parking_dummies.head(5)

,parking_carport,parking_detached garage,parking_no parking,parking_off-street parking,parking_street parking,parking_valet parking
0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0

In [38]:
yData = rentData.price
dataToStandardize = rentData[["sqfeet", "beds", "baths"]]

In [39]:
# Initialize the scaler
scaler = StandardScaler()
# Fit and transform the data
standardizedData = scaler.fit_transform(dataToStandardize)
# reapply indexes 
standardizedDataFrame = pandas.DataFrame(standardizedData, columns=["sqfeet", "beds", "baths"], index=dataToStandardize.index)
standardizedDataFrame.head(10)

     sqfeet      beds     baths
0  0.035300  0.294588  0.819622
1  0.009767  0.294588  0.819622
2  0.001705 -0.247140  0.026232
3 -0.007225 -0.247140 -0.767158
4 -0.002023  0.023724 -0.767158
5  0.008857  0.023724  0.819622
6  0.011111  0.023724  0.819622
7  0.052639  0.294588  0.819622
8  0.002702  0.294588  0.819622
9 -0.016935 -0.247140 -0.767158

In [40]:
xData = rentData[["cats_allowed", "dogs_allowed", "smoking_allowed", "wheelchair_access", "electric_vehicle_charge", "comes_furnished"]]

In [41]:
# join all data together for model
xData = xData.join([standardizedDataFrame, geo_dummies, type_dummies, laundry_dummies, parking_dummies])

In [42]:
xData

,cats_allowed,dogs_allowed,smoking_allowed,wheelchair_access,electric_vehicle_charge,comes_furnished,sqfeet,beds,baths,stateRegion_ak fairbanks,...,laundry_laundry on site,laundry_no laundry on site,laundry_w/d hookups,laundry_w/d in unit,parking_carport,parking_detached garage,parking_no parking,parking_off-street parking,parking_street parking,parking_valet parking
0,1,1,1,0,0,0,0.035300,0.294588,0.819622,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,1,1,0,0,0,0.009767,0.294588,0.819622,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1,1,1,0,0,0,0.001705,-0.247140,0.026232,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,1,1,0,0,0,-0.007225,-0.247140,-0.767158,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,1,1,0,0,0,-0.002023,0.023724,-0.767158,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265185,1,1,1,0,0,0,-0.001417,0.023724,0.819622,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
265186,1,1,1,0,0,0,-0.003194,0.023724,0.026232,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
265187,1,1,1,0,0,0,0.024549,0.023724,0.026232,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265188,1,1,1,0,0,0,0.005476,0.294588,0.026232,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
265189,1,1,0,0,0,0,0.008944,0.023724,1.613013,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
# create train / test split
X_train, X_test, y_train, y_test = train_test_split(xData, yData, test_size=0.2)

In [46]:
#define cross-validation method to evaluate model
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

#define model
model = LassoCV(alphas=numpy.arange(0, 1, 0.01), cv=cv, n_jobs=-1)

#fit model
model.fit(X_train, y_train)

C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 788107253929336.9, tolerance: 158355341735.8574
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 819237140453052.6, tolerance: 164617251751.4029
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290740162094454e+18, tolerance: 766498987057031.9
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828743314128982e+18, tolerance: 766430920917052.0
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829021180230589e+18, tolerance: 766500086409067.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829010010399027e+18, tolerance: 766497863649371.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828799349997651e+18, tolerance: 766450746492731.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8289875695653187e+18, tolerance: 766498882798329.0
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290584642916946e+18, tolerance: 766512116715832.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828990259322959e+18, tolerance: 766498744615936.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290807594945085e+18, tolerance: 766512103574538.5
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828884914954548e+18, tolerance: 766477965180112.9
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8289472433615104e+18, tolerance: 766478016881532.4
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829053091979847e+18, tolerance: 766504762918722.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290495914151327e+18, tolerance: 766512190685760.5
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290946983342715e+18, tolerance: 766512243588707.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 748020391043010.1, tolerance: 150298173515.11234
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829041739365328e+18, tolerance: 766504763357565.8
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8291368981124004e+18, tolerance: 766505972637387.8
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290794485728865e+18, tolerance: 766512278812228.4
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290259785815967e+18, tolerance: 766506491328545.6
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829049471280406e+18, tolerance: 766512174322274.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828938182615828e+18, tolerance: 766478044618364.0
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290682870412677e+18, tolerance: 766512123422603.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828662686906626e+18, tolerance: 766430917364264.1
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290962255597363e+18, tolerance: 766512079665785.6
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.829019952231267e+18, tolerance: 766512173781194.5
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828996844377455e+18, tolerance: 766498646760507.2
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8290834998312346e+18, tolerance: 766512085954397.1
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\Ryan\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:683: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.828914947499704e+18, tolerance: 766477919435881.2
  model = cd_fast.enet_coordinate_descent_gram(

LassoCV(alphas=array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99]),
        cv=RepeatedKFold(n_repeats=3, n_splits=10, random_state=1), n_jobs=-1)

In [47]:
# display lambda value
print(model.alpha_)

0.99

In [50]:
model = Lasso(alpha=0.99)
model.fit(X_train, y_train)

Lasso(alpha=0.99)

In [51]:
model.score(X_test, y_test)

-7.83285946137306

In [53]:
model = sm.OLS(y_train, X_train).fit()
print(model.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.001
Model:                            OLS   Adj. R-squared (uncentered):             -0.001
Method:                 Least Squares   F-statistic:                             0.5185
Date:                Sat, 07 Mar 2026   Prob (F-statistic):                        1.00
Time:                        20:36:32   Log-Likelihood:                     -3.6124e+06
No. Observations:              212152   AIC:                                  7.226e+06
Df Residuals:                  211816   BIC:                                  7.229e+06
Df Model:                         336
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
cats_allowed                                1.65e+04   6.58e+04      0.251      0.802   -1.12e+05    1.45e+05
dogs_allowed                                1.68e+04   6.43e+04      0.261      0.794   -1.09e+05    1.43e+05
smoking_allowed                            1.765e+04   3.33e+04      0.529      0.597   -4.77e+04     8.3e+04
wheelchair_access                         -3.026e+04   5.29e+04     -0.572      0.567   -1.34e+05    7.34e+04
electric_vehicle_charge                    1.978e+04   1.16e+05      0.170      0.865   -2.08e+05    2.47e+05
comes_furnished                           -1.169e+04   6.46e+04     -0.181      0.856   -1.38e+05    1.15e+05
sqfeet                                       54.4064   1.18e+04      0.005      0.996   -2.31e+04    2.32e+04
beds                                       -186.6669   1.62e+04     -0.012      0.991   -3.18e+04    3.15e+04
baths                                       745.2054   1.64e+04      0.046      0.964   -3.13e+04    3.28e+04
stateRegion_ak fairbanks                  -4.368e+04   3.88e+05     -0.113      0.910   -8.03e+05    7.16e+05
stateRegion_ak kenai peninsula            -3.291e+04    7.1e+05     -0.046      0.963   -1.43e+06    1.36e+06
stateRegion_ak southeast alaska           -3.557e+04   7.41e+05     -0.048      0.962   -1.49e+06    1.42e+06
stateRegion_al birmingham                 -7.435e+04   2.93e+05     -0.254      0.800   -6.48e+05       5e+05
stateRegion_al dothan                     -7.025e+04   6.15e+05     -0.114      0.909   -1.28e+06    1.14e+06
stateRegion_al florence / muscle shoals   -6.866e+04   8.88e+05     -0.077      0.938   -1.81e+06    1.67e+06
stateRegion_al gadsden-anniston           -8.707e+04   8.05e+05     -0.108      0.914   -1.66e+06    1.49e+06
stateRegion_al huntsville / decatur       -9.304e+04   1.53e+05     -0.607      0.544   -3.93e+05    2.07e+05
stateRegion_al mobile                     -7.862e+04   1.67e+05     -0.470      0.638   -4.06e+05    2.49e+05
stateRegion_al montgomery                 -7.769e+04   2.47e+05     -0.314      0.753   -5.62e+05    4.07e+05
stateRegion_al tuscaloosa                 -9.062e+04   2.52e+05     -0.360      0.719   -5.84e+05    4.02e+05
stateRegion_ar fayetteville               -4.433e+04   2.13e+05     -0.208      0.835   -4.61e+05    3.73e+05
stateRegion_ar fort smith                 -6.165e+04   5.34e+05     -0.115      0.908   -1.11e+06    9.85e+05
stateRegion_ar jonesboro                  -3.462e+04   5.32e+05     -0.065      0.948   -1.08e+06    1.01e+06
stateRegion_ar little rock                -8.481e+04   1.69e+05     -0.502      0.615   -4.16e+05    2.46e+05
stateRegion_ar texarkana                  -1.024e+05   7.01e+05     -0.146      0.884   -1.48e+06    1.27e+06
stateRegion_az flagstaff / sedona         -5.942e+04   2.24e+05     -0.266      0.791   -4.98e+05    3.79e+05
stateRegion_az mohave county              -7.182e+04   3.05e+05     -0.236      0.814   -6.69e+05    5.26e+05
stateRegion_az phoenix                     -4.66e+04   1.55e+05     -0.300      0.764   -3.51e+05    2.57e+05
stateRegion_az prescott                   -4.634e+04   5.27e+05     -0.088      0.930   -1.08e+06    9.87e+05
stateRegion_az show low                   -9.861e+04   6.66e+05     -0.148      0.882    -1.4e+06    1.21e+06
stateRegion_az sierra vista                -5.42e+04   3.64e+05     -0.149      0.882   -7.68e+05    6.59e+05
stateRegion_az tucson                     -5.672e+04   1.44e+05     -0.393      0.694    -3.4e+05    2.26e+05
stateRegion_az yuma                       -4.019e+04   4.63e+05     -0.087      0.931   -9.48e+05    8.68e+05
stateRegion_ca SF bay area                -3.358e+04   1.46e+05     -0.231      0.818   -3.19e+05    2.52e+05
stateRegion_ca bakersfield                -4.601e+04   1.72e+05     -0.267      0.789   -3.84e+05    2.92e+05
stateRegion_ca chico                      -5.373e+04   4.18e+05     -0.128      0.898   -8.74e+05    7.66e+05
stateRegion_ca fresno / madera            -4.818e+04   1.51e+05     -0.319      0.750   -3.44e+05    2.48e+05
stateRegion_ca gold country                 -5.2e+04   4.22e+05     -0.123      0.902    -8.8e+05    7.76e+05
stateRegion_ca hanford-corcoran           -4.308e+04    2.4e+05     -0.180      0.858   -5.14e+05    4.27e+05
stateRegion_ca humboldt county             -5.26e+04   5.63e+05     -0.093      0.926   -1.16e+06    1.05e+06
stateRegion_ca imperial county              -9.4e+04   6.88e+05     -0.137      0.891   -1.44e+06    1.25e+06
stateRegion_ca inland empire              -3.884e+04   1.41e+05     -0.276      0.782   -3.14e+05    2.37e+05
stateRegion_ca los angeles                -3.929e+04   1.48e+05     -0.266      0.790   -3.28e+05     2.5e+05
stateRegion_ca mendocino county           -4.864e+04   8.69e+05     -0.056      0.955   -1.75e+06    1.65e+06
stateRegion_ca merced                      -3.53e+04   4.08e+05     -0.087      0.931   -8.34e+05    7.64e+05
stateRegion_ca modesto                    -5.641e+04   1.97e+05     -0.286      0.775   -4.43e+05    3.31e+05
stateRegion_ca monterey bay               -4.557e+04   2.05e+05     -0.222      0.824   -4.47e+05    3.56e+05
stateRegion_ca orange county              -4.423e+04   1.45e+05     -0.305      0.760   -3.28e+05     2.4e+05
stateRegion_ca palm springs               -4.797e+04   1.87e+05     -0.257      0.797   -4.14e+05    3.18e+05
stateRegion_ca redding                    -4.858e+04   4.44e+05     -0.109      0.913   -9.19e+05    8.22e+05
stateRegion_ca reno / tahoe               -4.803e+04   1.57e+05     -0.306      0.760   -3.56e+05     2.6e+05
stateRegion_ca sacramento                 -4.797e+04   1.45e+05     -0.331      0.741   -3.32e+05    2.36e+05
stateRegion_ca san diego                  -4.292e+04   1.44e+05     -0.299      0.765   -3.24e+05    2.39e+05
stateRegion_ca san luis obispo            -5.734e+04    3.2e+05     -0.179      0.858   -6.85e+05     5.7e+05
stateRegion_ca santa barbara              -4.805e+04   2.75e+05     -0.175      0.861   -5.86e+05     4.9e+05
stateRegion_ca santa maria                -6.497e+04   5.91e+05     -0.110      0.913   -1.22e+06    1.09e+06
stateRegion_ca siskiyou county            -2.191e+04   1.02e+06     -0.022      0.983   -2.02e+06    1.97e+06
stateRegion_ca stockton                   -6.002e+04   1.43e+05     -0.419      0.675   -3.41e+05    2.21e+05
stateRegion_ca susanville                 -4.218e+04   1.61e+06     -0.026      0.979   -3.19e+06    3.11e+06
stateRegion_ca ventura county             -4.605e+04    1.4e+05     -0.329      0.742    -3.2e+05    2.28e+05
stateRegion_ca visalia-tulare              -5.94e+04   3.28e+05     -0.181      0.856   -7.01e+05    5.83e+05
stateRegion_ca yuba-sutter                -6.788e+04   5.49e+05     -0.124      0.902   -1.14e+06    1.01e+06
stateRegion_co boulder                    -4.436e+04   1.36e+05     -0.326      0.745   -3.11e+05    2.22e+05
stateRegion_co colorado springs           -6.362e+04   1.39e+05     -0.456      0.648   -3.37e+05     2.1e+05
stateRegion_co denver                      -4.52e+04   1.35e+05     -0.334      0.738    -3.1e+05     2.2e+05
stateRegion_co eastern CO                 -1.029e+05    9.3e+05     -0.111      0.912   -1.93e+06    1.72e+06
stateRegion_co fort collins / north CO    -6.503e+04   1.38e+05     -0.471      0.638   -3.36e+05    2.06e+05
stateRegion_co high rockies               -2.963e+04    4.2e+05     -0.071      0.944   -8.53e+05    7.93e+05
stateRegion_co pueblo                     -5.803e+04    4.2e+05     -0.138      0.890   -8.81e+05    7.65e+05
stateRegion_co western slope              -4.499e+04   3.49e+05     -0.129      0.898    -7.3e+05     6.4e+05
stateRegion_ct eastern CT                 -8.388e+04   2.64e+05     -0.317      0.751   -6.02e+05    4.34e+05
stateRegion_ct hartford                   -6.271e+04    1.8e+05     -0.349      0.727   -4.15e+05     2.9e+05
stateRegion_ct new haven                  -6.972e+04   1.83e+05     -0.381      0.703   -4.28e+05    2.89e+05
stateRegion_ct northwest CT               -6.583e+04   5.14e+05     -0.128      0.898   -1.07e+06    9.41e+05
stateRegion_dc washington, DC             -4.387e+04   1.41e+05     -0.312      0.755    -3.2e+05    2.32e+05
stateRegion_de delaware                   -4.367e+04   1.55e+05     -0.282      0.778   -3.47e+05    2.59e+05
stateRegion_fl daytona beach              -7.147e+04   1.47e+05     -0.488      0.626   -3.59e+05    2.16e+05
stateRegion_fl florida keys               -3.623e+04   3.24e+05     -0.112      0.911   -6.72e+05       6e+05
stateRegion_fl ft myers / SW florida      -5.292e+04   1.54e+05     -0.343      0.732   -3.55e+05     2.5e+05
stateRegion_fl gainesville                -5.115e+04   1.55e+05     -0.329      0.742   -3.56e+05    2.53e+05
stateRegion_fl heartland florida          -2.895e+04   4.25e+05     -0.068      0.946   -8.63e+05    8.05e+05
stateRegion_fl jacksonville               -6.203e+04   1.38e+05     -0.450      0.653   -3.32e+05    2.08e+05
stateRegion_fl lakeland                   -7.341e+04   1.48e+05     -0.495      0.621   -3.64e+05    2.17e+05
stateRegion_fl north central FL            2.264e+05   1.16e+06      0.195      0.845   -2.04e+06     2.5e+06
stateRegion_fl ocala                      -8.366e+04   2.88e+05     -0.291      0.771   -6.48e+05     4.8e+05
stateRegion_fl okaloosa / walton          -1.078e+05   2.24e+05     -0.482      0.630   -5.46e+05     3.3e+05
stateRegion_fl orlando                     -4.64e+04   1.38e+05     -0.336      0.737   -3.17e+05    2.25e+05
stateRegion_fl panama city                -7.765e+04   1.71e+05     -0.453      0.650   -4.14e+05    2.58e+05
stateRegion_fl pensacola                  -9.833e+04   1.75e+05     -0.563      0.573    -4.4e+05    2.44e+05
stateRegion_fl sarasota-bradenton         -6.888e+04   1.43e+05     -0.481      0.630   -3.49e+05    2.12e+05
stateRegion_fl south florida              -4.253e+04   1.83e+05     -0.233      0.816   -4.01e+05    3.16e+05
stateRegion_fl space coast                -7.003e+04   1.41e+05     -0.496      0.620   -3.47e+05    2.07e+05
stateRegion_fl st augustine               -5.729e+04   4.78e+05     -0.120      0.905   -9.95e+05     8.8e+05
stateRegion_fl tallahassee                -6.332e+04   1.58e+05     -0.401      0.689   -3.73e+05    2.46e+05
stateRegion_fl tampa bay area             -5.594e+04   1.51e+05     -0.370      0.712   -3.53e+05    2.41e+05
stateRegion_fl treasure coast             -5.813e+04   1.66e+05     -0.350      0.726   -3.84e+05    2.67e+05
stateRegion_ga albany                     -1.373e+05   2.38e+05     -0.578      0.564   -6.03e+05    3.29e+05
stateRegion_ga athens                     -1.092e+05   2.03e+05     -0.538      0.591   -5.07e+05    2.89e+05
stateRegion_ga atlanta                    -6.175e+04   1.48e+05     -0.416      0.677   -3.53e+05    2.29e+05
stateRegion_ga augusta                    -8.574e+04   1.41e+05     -0.610      0.542   -3.61e+05     1.9e+05
stateRegion_ga brunswick                  -8.026e+04   4.78e+05     -0.168      0.867   -1.02e+06    8.57e+05
stateRegion_ga columbus                    2.105e+06   1.72e+05     12.234      0.000    1.77e+06    2.44e+06
stateRegion_ga macon / warner robins      -7.564e+04   1.76e+05     -0.430      0.668   -4.21e+05    2.69e+05
stateRegion_ga northwest GA               -7.004e+04    3.2e+05     -0.219      0.827   -6.98e+05    5.58e+05
stateRegion_ga savannah / hinesville      -9.679e+04   1.41e+05     -0.685      0.494   -3.74e+05     1.8e+05
stateRegion_ga statesboro                 -5.236e+04   9.77e+05     -0.054      0.957   -1.97e+06    1.86e+06
stateRegion_ga valdosta                   -7.986e+04   2.96e+05     -0.269      0.788   -6.61e+05    5.01e+05
stateRegion_hi hawaii                     -3.136e+04   1.61e+05     -0.195      0.845   -3.46e+05    2.84e+05
stateRegion_ia ames                       -6.382e+04   3.65e+05     -0.175      0.861   -7.79e+05    6.51e+05
stateRegion_ia cedar rapids               -6.156e+04   2.48e+05     -0.248      0.804   -5.48e+05    4.25e+05
stateRegion_ia des moines                 -4.867e+04   1.45e+05     -0.337      0.736   -3.32e+05    2.35e+05
stateRegion_ia dubuque                    -4.352e+04    7.3e+05     -0.060      0.952   -1.48e+06    1.39e+06
stateRegion_ia fort dodge                 -5.836e+04   6.36e+05     -0.092      0.927   -1.31e+06    1.19e+06
stateRegion_ia iowa city                  -6.233e+04   3.44e+05     -0.181      0.856   -7.36e+05    6.11e+05
stateRegion_ia mason city                 -3.969e+04   1.35e+06     -0.029      0.976   -2.68e+06     2.6e+06
stateRegion_ia omaha / council bluffs     -6.128e+04   1.35e+05     -0.455      0.649   -3.25e+05    2.03e+05
stateRegion_ia sioux city                 -5.474e+04   3.29e+05     -0.166      0.868      -7e+05    5.91e+05
stateRegion_ia southeast IA               -5.394e+04   9.07e+05     -0.059      0.953   -1.83e+06    1.72e+06
stateRegion_ia waterloo / cedar falls     -5.185e+04   3.92e+05     -0.132      0.895    -8.2e+05    7.16e+05
stateRegion_id boise                      -4.843e+04    1.8e+05     -0.269      0.788   -4.01e+05    3.04e+05
stateRegion_id east idaho                 -5.573e+04   3.68e+05     -0.152      0.880   -7.76e+05    6.65e+05
stateRegion_id lewiston / clarkston       -6.184e+04   1.28e+06     -0.048      0.962   -2.58e+06    2.45e+06
stateRegion_id pullman / moscow           -4.827e+04   4.52e+05     -0.107      0.915   -9.34e+05    8.37e+05
stateRegion_id spokane / coeur d'alene     -5.17e+04   1.47e+05     -0.351      0.725    -3.4e+05    2.37e+05
stateRegion_id twin falls                 -5.596e+04   6.91e+05     -0.081      0.935   -1.41e+06     1.3e+06
stateRegion_il bloomington-normal         -6.527e+04   3.16e+05     -0.207      0.836   -6.84e+05    5.53e+05
stateRegion_il champaign urbana            -4.83e+04   1.53e+05     -0.316      0.752   -3.48e+05    2.52e+05
stateRegion_il chicago                    -4.711e+04   1.77e+05     -0.266      0.791   -3.95e+05       3e+05
stateRegion_il decatur                    -8.339e+04   3.84e+05     -0.217      0.828   -8.37e+05     6.7e+05
stateRegion_il la salle co                -4.622e+04   1.12e+06     -0.041      0.967   -2.24e+06    2.14e+06
stateRegion_il mattoon-charleston          -5.26e+04   1.05e+06     -0.050      0.960   -2.11e+06       2e+06
stateRegion_il peoria                     -6.054e+04   3.17e+05     -0.191      0.849   -6.82e+05    5.61e+05
stateRegion_il quad cities, IA/IL           -5.1e+04   1.93e+05     -0.265      0.791   -4.29e+05    3.27e+05
stateRegion_il rockford                    -5.86e+04   3.41e+05     -0.172      0.863   -7.27e+05    6.09e+05
stateRegion_il southern illinois          -6.471e+04   3.45e+05     -0.187      0.851   -7.41e+05    6.12e+05
stateRegion_il springfield                -6.391e+04   3.82e+05     -0.167      0.867   -8.13e+05    6.85e+05
stateRegion_il st louis, MO               -7.647e+04   1.45e+05     -0.528      0.597    -3.6e+05    2.07e+05
stateRegion_il western IL                 -7.592e+04   1.35e+06     -0.056      0.955   -2.71e+06    2.56e+06
stateRegion_in bloomington                -7.743e+04   2.72e+05     -0.285      0.776    -6.1e+05    4.55e+05
stateRegion_in evansville                 -5.343e+04   1.89e+05     -0.283      0.777   -4.24e+05    3.17e+05
stateRegion_in fort wayne                 -6.164e+04   2.47e+05     -0.250      0.803   -5.46e+05    4.22e+05
stateRegion_in indianapolis               -6.953e+04   1.52e+05     -0.456      0.648   -3.68e+05    2.29e+05
stateRegion_in kokomo                     -8.471e+04   7.36e+05     -0.115      0.908   -1.53e+06    1.36e+06
stateRegion_in lafayette / west lafayette -6.305e+04   3.97e+05     -0.159      0.874   -8.42e+05    7.16e+05
stateRegion_in muncie / anderson           -7.56e+04   3.99e+05     -0.189      0.850   -8.58e+05    7.07e+05
stateRegion_in richmond                    -7.49e+04   6.87e+05     -0.109      0.913   -1.42e+06    1.27e+06
stateRegion_in south bend / michiana      -6.397e+04   2.61e+05     -0.245      0.806   -5.76e+05    4.48e+05
stateRegion_in terre haute                -7.471e+04   6.74e+05     -0.111      0.912    -1.4e+06    1.25e+06
stateRegion_ks kansas city, MO            -7.292e+04   1.64e+05     -0.444      0.657   -3.95e+05    2.49e+05
stateRegion_ks lawrence                   -7.587e+04   2.97e+05     -0.256      0.798   -6.57e+05    5.06e+05
stateRegion_ks manhattan                  -8.797e+04    2.1e+05     -0.418      0.676      -5e+05    3.24e+05
stateRegion_ks northwest KS               -8.086e+04   7.36e+05     -0.110      0.913   -1.52e+06    1.36e+06
stateRegion_ks salina                     -4.984e+04   1.25e+06     -0.040      0.968   -2.51e+06    2.41e+06
stateRegion_ks southeast KS               -5.646e+04   6.03e+05     -0.094      0.925   -1.24e+06    1.13e+06
stateRegion_ks southwest KS               -3.628e+04   9.77e+05     -0.037      0.970   -1.95e+06    1.88e+06
stateRegion_ks topeka                     -6.506e+04   1.47e+05     -0.442      0.659   -3.54e+05    2.24e+05
stateRegion_ks wichita                    -6.831e+04   1.57e+05     -0.435      0.663   -3.76e+05    2.39e+05
stateRegion_ky bowling green              -7.123e+04   2.15e+05     -0.332      0.740   -4.92e+05     3.5e+05
stateRegion_ky eastern kentucky            -7.48e+04   9.52e+05     -0.079      0.937   -1.94e+06    1.79e+06
stateRegion_ky huntington-ashland         -7.969e+04   5.78e+05     -0.138      0.890   -1.21e+06    1.05e+06
stateRegion_ky lexington                  -9.387e+04   1.49e+05     -0.630      0.529   -3.86e+05    1.98e+05
stateRegion_ky louisville                 -9.461e+04   1.63e+05     -0.582      0.561   -4.13e+05    2.24e+05
stateRegion_ky owensboro                  -5.273e+04    1.5e+06     -0.035      0.972      -3e+06    2.89e+06
stateRegion_ky western KY                  -8.96e+04   7.71e+05     -0.116      0.908    -1.6e+06    1.42e+06
stateRegion_la baton rouge                -6.844e+04   1.62e+05     -0.423      0.672   -3.86e+05    2.49e+05
stateRegion_la central louisiana          -5.146e+04   6.78e+05     -0.076      0.940   -1.38e+06    1.28e+06
stateRegion_la houma                      -5.711e+04   4.42e+05     -0.129      0.897   -9.24e+05    8.09e+05
stateRegion_la lafayette                  -9.693e+04   1.75e+05     -0.555      0.579   -4.39e+05    2.45e+05
stateRegion_la lake charles                -5.79e+04   3.55e+05     -0.163      0.870   -7.54e+05    6.38e+05
stateRegion_la monroe                     -6.484e+04    4.5e+05     -0.144      0.885   -9.46e+05    8.16e+05
stateRegion_la new orleans                -6.163e+04   1.54e+05     -0.399      0.690   -3.64e+05    2.41e+05